FROM node:20-alpine3.20 AS build

WORKDIR /build

COPY package.json package-lock.json ./

RUN npm ci

COPY tsconfig.json ./
COPY src/ ./src/

RUN npm run build

RUN npm ci --production

FROM node:20-alpine3.20 AS runtime

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY .env ./

COPY --from=build /build/dist ./dist
COPY --from=build /build/node_modules ./node_modules

RUN chown -R appuser:appgroup /app

EXPOSE 8082

USER appuser

CMD ["node", "dist/index.js"]